Add GitHub buttons + navigation to submodel templates
admin-shell-io/aas-specs-antora-ui pull request #7
Opened 2024-10-27 13:13 UTC by monsieuremre

Changes:

* Added the option navigate between two documentation websites directly within the UI. It is meant to be the main way of navigating between aas-specs and submodels documentation sites. As of now, the submodels site is a deadlink, but it will work as soon as the submodel website gets up.

* Added new button to directly report an issue from the website
* Added new button to directly see the history of the current source from the website

* Added logo for the history button
* Added logo for the issue report button
* Added logo for the edit this page button
* Added logo for the generate pdf button

* Created uniform theming for all the buttons

* Small fixes and changes

2024-10-27 13:14 UTC, monsieuremre commented
Lightbox modal view is not included in the request as it is not  yet ready.

2024-10-28 14:10 UTC, zrgt requested changes

2024-10-28 14:10 UTC, zrgt commented on .github/workflows/release.yml
> +      github.repository == 'rwth-iat/aas-specs-antora-ui' && !startsWith(github.event.head_commit.message, 'Release ')
```suggestion
      github.repository == 'admin-shell-io/aas-specs-antora-ui' && !startsWith(github.event.head_commit.message, 'Release ')
```

2024-10-28 14:10 UTC, zrgt commented on package.json
> +  "homepage": "https://github.com/rwth-iat/aas-specs-antora-ui/blob/main/package.json",
```suggestion
  "homepage": "https://github.com/admin-shell-io/aas-specs-antora-ui/blob/main/package.json",
```

2024-10-28 14:10 UTC, zrgt commented on package.json
> +    "url": "https://github.com/rwth-iat/aas-specs-antora-ui/blob/main/package.json"
```suggestion
    "url": "https://github.com/admin-shell-io/aas-specs-antora-ui/blob/main/package.json"
```

2024-10-28 14:11 UTC, zrgt approved these changes

2024-10-28 14:15 UTC, merged